services:
  - type: web
    name: mlflow
    env: docker
    plan: free
    dockerfilePath: app/Dockerfile
    envVars:
      - key: BACKEND_STORE_URI
        value: <postgresql://pk:fEqmHb5cCTtvRpeOCGERx9amFXn9Ilv8@dpg-ctnel85umphs73c5ufm0-a.singapore-postgres.render.com/mlflow_0fna>  # Set Render database URL
      - key: ARTIFACT_STORE_URI
        
    port: 5000

